language: nix

os:
  - linux
  - osx

# It's a bit wasteful, in Travis terms, to build each version in a
# separate job, but this allows a clear overview of which individual
# versions are not working, and ultimately we hope to not be building
# often.
env:
  matrix:
    - ATTR=emacs-23-4
    - ATTR=emacs-24-1
    - ATTR=emacs-24-2
    - ATTR=emacs-24-3
    - ATTR=emacs-24-4
    - ATTR=emacs-24-5
    - ATTR=emacs-25-1
    - ATTR=emacs-25-2
    - ATTR=emacs-25-3
    - ATTR=emacs-26-1
    - ATTR=emacs-26-2
    - ATTR=emacs-26-3
    - ATTR=emacs-snapshot

matrix:
  exclude:
  - os: osx
    env: ATTR=emacs-24-1
  - os: osx
    env: ATTR=emacs-23-4
  - os: osx
    env: ATTR=emacs-24-2

install:
  ./travis-install

script:
  - |
    set -e
    nix-build -A $ATTR | tee output
    EMACS=$PWD/result/bin/emacs tests/run
    if [ -n "$CACHIX_SIGNING_KEY" ] && [ "$TRAVIS_REPO_SLUG" = "purcell/nix-emacs-ci" ]; then
      cachix push emacs-ci < output
    fi
