name: Update snapshot

on:
  schedule:
    - cron: "15 9 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Update snapshot commit
      run: nix-shell -p niv niv update emacs-snapshot
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        title: 'Update snapshot'
        add-paths: nix/sources.*
